version: '3'
services:
    node-express:
        container_name: node-express-docker-cont
        build: .
        ports:
            - "3000:3000"
        environment:
            - LOG_LVL=WARN
        env_file:
            - ./.env