version: '3'
services:
    node-express:
        container_name: node-express-docker-cont
        image: anweress/test-nodejs:v1.0.1
        build: .
        volumes:
            - ./src:/app/src:ro
        ports:
            - "3000:3000"
        environment:
            - LOG_LVL=WARN
        env_file:
            - ./.env
        depends_on:
            - mongo
            - postgres
    mongo:
        image: mongo
        restart: always
        volumes:
            - mongo-db:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: "mongodb"
            MONGO_INITDB_ROOT_PASSWORD: "mongodb"
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: mongodb
            ME_CONFIG_MONGODB_ADMINPASSWORD: mongodb
            ME_CONFIG_MONGODB_URL: mongodb://mongodb:mongodb@mongodb27017/
        depends_on:
            - mongo
    redis:
        image: redis
    postgres:
        image: postgres
        volumes:
            - postgres-db:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
volumes:
    mongo-db:
    postgres-db: